server:
  port: 8081
spring:
  application:
    name: CompanyService
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/companyservice
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka